module.exports = {
  secret: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtb2JpbGVubyI6Ijk3ODg2NDM5MDciLCJuYW1lIjoiRGhhbnZpa2F2aSIsImlhdCI6MTUxNjIzOTAyMn0.B0YC5CKjvRUYUxT3PMDf9BBeNnZBtpyuJCJcWj_LyRU"
};


